// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MenuPlugin","status":true,"description":"","parameters":{}},
{"name":"BattlePlugin","status":true,"description":"","parameters":{}},
{"name":"Window","status":true,"description":"","parameters":{}},
{"name":"SpriteButton","status":true,"description":"","parameters":{}},
{"name":"Controls","status":true,"description":"","parameters":{}}
];
